# Generated by Django 2.0.2 on 2018-09-12 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteSongModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'favorite_song',
            },
        ),
        migrations.CreateModel(
            name='ShowModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('thumbnail', models.CharField(max_length=200)),
                ('download', models.IntegerField(default=0)),
                ('type_ads', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'show',
            },
        ),
        migrations.CreateModel(
            name='SingerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.CharField(default=None, max_length=200, null=True)),
            ],
            options={
                'db_table': 'singer',
            },
        ),
        migrations.CreateModel(
            name='SingerSongModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singer_song_id_singer', to='data.SingerModel')),
            ],
            options={
                'db_table': 'singer_song',
            },
        ),
        migrations.CreateModel(
            name='SongModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('thumbnail', models.CharField(max_length=200)),
                ('duration', models.IntegerField(default=0)),
                ('view', models.IntegerField(default=0)),
                ('auth', models.ManyToManyField(through='data.SingerSongModel', to='data.SingerModel')),
            ],
            options={
                'db_table': 'song',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('fb', models.CharField(default=None, max_length=200, null=True)),
                ('avatar', models.CharField(default=None, max_length=200, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='songmodel',
            name='favorite',
            field=models.ManyToManyField(through='data.FavoriteSongModel', to='data.UserModel'),
        ),
        migrations.AddField(
            model_name='singersongmodel',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singer_song_id_song', to='data.SongModel'),
        ),
        migrations.AddField(
            model_name='favoritesongmodel',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_song_id_song', to='data.SongModel'),
        ),
        migrations.AddField(
            model_name='favoritesongmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_song_id_user', to='data.UserModel'),
        ),
    ]
