# Generated by Django 2.0.2 on 2018-09-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='avatar',
            field=models.TextField(default=None, max_length=200, null=True),
        ),
    ]
